### ISSUE TITLE
Documentation incorrect for loading the extension in browser

### ISSUE THREAD

**Issue by FitzM** [amazingmarvin/amazingmarvin-browserextension#19]
I followed the instructions in "Loading the extension in your browser" section, once `npm run build` was run, there was no ` dist` directory, only a chromium.zip file.  Extracting the file and loading that worked. 

Also, `npm start` fails to be able to be loaded into the browser with the error of " Service worker registration failed. Status code: 3".  I'm unsure if there is a different way to develop the extensions without having to build it every time and then unzip the file.

**Comment by rijavecb** [comment]
Hi @FitzM. Thank you for reporting this issue. I just tried it and here are some observations:

- When you run `npm run build` that will create a new directory called `out`, with `prod` folder inside it. Could you try to load that folder into your browser? I see that README mentions `dist` which got replace with `out`, so I'll update that.
- About that service worker error message, that one seems to be happening due to [Chromium's lack of support](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings) for `browser_specific_settings`. Could you open the extension's `manifest.json` file and remove `browser_specific_settings` key from it? That should get rid of that error and I'll see with Mark how we can improve this, perhaps by programmatically adding it to manifest when running `ff:build`

![image](https://github.com/amazingmarvin/amazingmarvin-browserextension/assets/15850530/6001987f-a399-435e-a790-b083ec294dc8)

**Comment by FitzM** [comment]
I've removed the browser specific line however I still get the error in Chrome.  I know I read ( can't find it currently) that Chrome doesn't allow for the service worker to be in a nested directory.

**Comment by mltucker** [comment]
I just tried this out and got it working with a fresh chrome profile, version 120.0.6099.109.

* `npm run start`
* Open chrome://extensions
* Turn on developer mode
* Click "Load unpacked"
* Choose `amazingmarvin-browserextension/out/dev`

Did you use this procedure?

**Comment by FitzM** [comment]
> I just tried this out and got it working with a fresh chrome profile, version 120.0.6099.109.
> 
> * `npm run start`
> * Open chrome://extensions
> * Turn on developer mode
> * Click "Load unpacked"
> * Choose `amazingmarvin-browserextension/out/dev`
> 
> Did you use this procedure?

Thank you. Somehow,  I wasn't getting a dev directory previously, it was only showing prod. I'm sure that's a mistake on my part. 

I'm trying to integrate full calendar into the add on view to manage my calendar easily. Thanks.
